/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webbrowser.gui;

import java.awt.BorderLayout;
import javax.swing.table.DefaultTableModel;
import webbrowser.database.FazConsulta;
import webbrowser.database.ListaConsulta;
import webbrowser.model.HistoricoTableModel;
import webbrowser.model.Historico;

/**
 *
 * @author andre
 */
public class TabHistorico extends javax.swing.JPanel {

    private Object displayEditorPane;
    HistoricoTableModel HistoricoTable = new HistoricoTableModel();

    /**
     * Creates new form TabHistorico
     */
    public TabHistorico() {
        initComponents();
        jTableHistorico.setModel(HistoricoTable);
        FazConsulta f = new FazConsulta();
        f.fazConsultaSQL("select * from historico");
        carrega();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHistorico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHistorico = new javax.swing.JTable();
        jButtonLimpaTudo = new javax.swing.JButton();
        jButtonExcluiSelecionado = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTableHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableHistorico);

        jButtonLimpaTudo.setText("Limpar tudo");
        jButtonLimpaTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpaTudoActionPerformed(evt);
            }
        });

        jButtonExcluiSelecionado.setText("Excluir Selecionado");
        jButtonExcluiSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluiSelecionadoActionPerformed(evt);
            }
        });

        jButton4.setText("Fechar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHistoricoLayout = new javax.swing.GroupLayout(jPanelHistorico);
        jPanelHistorico.setLayout(jPanelHistoricoLayout);
        jPanelHistoricoLayout.setHorizontalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addGroup(jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExcluiSelecionado)
                    .addComponent(jButtonLimpaTudo))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanelHistoricoLayout.setVerticalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExcluiSelecionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpaTudo)
                    .addComponent(jButton4)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpaTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpaTudoActionPerformed
        if (jTableHistorico.getRowCount() > 0) {

             do {
                jTableHistorico.removeRowSelectionInterval(0, 0);
            } while (jTableHistorico.getRowCount() > 0);
        }
    }//GEN-LAST:event_jButtonLimpaTudoActionPerformed

    private void jButtonExcluiSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluiSelecionadoActionPerformed
        Historico h = new Historico();
        h = HistoricoTable.getColunaSelecionada(jTableHistorico.getSelectedRow());
        HistoricoTable.DeleteRowInTable(h);
    }//GEN-LAST:event_jButtonExcluiSelecionadoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanelHistorico.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed
public void carrega() {

        if (jTableHistorico.getRowCount() > 0) {

            do {
                jTableHistorico.removeRowSelectionInterval(0, 0);
            } while (jTableHistorico.getRowCount() > 0);

        }
        for (int i = 0; i < ListaConsulta.aList.size(); i++) {
            HistoricoTable.addRowInTable(ListaConsulta.aList.get(i));
        }

    }

    public void apaga() {

        if (jTableHistorico.getRowCount() > 0) {

            do {
                ((DefaultTableModel) jTableHistorico.getModel()).removeRow(0);
            } while (jTableHistorico.getRowCount() > 0);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonExcluiSelecionado;
    private javax.swing.JButton jButtonLimpaTudo;
    private javax.swing.JPanel jPanelHistorico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHistorico;
    // End of variables declaration//GEN-END:variables
}
